import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Marquee from "@/components/layout/Marquee";
// import Navbar from "@/components/layout/Navbar";
// import Footer from "@/components/layout/Footer";

const PPMori = localFont({
  src: "./fonts/PPMori-Regular.otf",
  display: "optional",
  variable: "--font-pp-mori",
  adjustFontFallback: false,
  fallback: [
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Arial",
    "sans-serif",
  ],
  preload: true,
});

const CSBohemian = localFont({
  src: "./fonts/CSBohemian-Regular.otf",
  display: "optional",
  variable: "--font-cs-bohemian",
  adjustFontFallback: false,
  fallback: [
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Arial",
    "sans-serif",
  ],
  preload: true,
});

export const metadata: Metadata = {
  title: "Lampros Labs Dao",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${CSBohemian.variable} ${PPMori.variable}`}>
        <Marquee text="Driving Mainstream Adoption, Empowering Developers, and Cultivating the Future of Web3" />
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
